CREATE TABLE post_office (
                             id bigint primary key generated by default as identity,
                             index varchar not null unique,
                             name varchar not null,
                             address varchar not null
);

CREATE TABLE type(
                     id int primary key generated by default as identity,
                     name varchar not null unique
);
CREATE TABLE post_item (
                           id bigint primary key generated by default as identity,
                           type_id int references type(id),
                           zip int not null,
                           address varchar not null,
                           name varchar not null,
                           status int not null
);

CREATE TABLE post_movement (
                               id bigint PRIMARY KEY generated by default as identity,
                               movement_type VARCHAR NOT NULL,
                               movement_date TIMESTAMP NOT NULL,
                               post_item_id INT,
                               post_office_id INT,
                               status int,
                               FOREIGN KEY (post_item_id) REFERENCES post_item(id),
                               FOREIGN KEY (post_office_id) REFERENCES post_office(id)
);